version: "3.9"

networks:
  teamcity-network:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24

services:
  server:
    image: ${DOCKER_HUB_USER}/teamcity-server:latest
    restart: unless-stopped
    build:
      context: .
      dockerfile: ../teamcity_server/dockerfile/teamcity_server.Dockerfile
    environment:
      - TEAMCITY_SERVER_MEM_OPTS=-Xmx3g -XX:MaxPermSize=270m -XX:ReservedCodeCacheSize=450m
    volumes:
      - ${SERVER_DATA_VOLUME_DIR}:/data/teamcity_server/datadir
      - ${SERVER_LOGS_VOLUME_DIR}:/opt/teamcity/logs
    ports:
      - '8111:8111'
    networks:
      teamcity-network:
        ipv4_address: 172.20.0.6

  postgres:
    image: ${DOCKER_HUB_USER}/teamcity-database:latest
    build:
      context: .
      dockerfile: ../teamcity_database/dockerfile/teamcity_database.Dockerfile
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=teamcity
      - POSTGRES_DB=teamcity
    volumes:
      - ${DATABASE_DATA_VOLUME_DIR}:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      teamcity-network:
        ipv4_address: 172.20.0.8

  agent1:
    image: ${DOCKER_HUB_USER}/teamcity-agent:latest
    restart: unless-stopped
    environment:
      - SERVER_URL=http://server:8111
    volumes:
      - ${AGENT_CONF_VOLUME_DIR}:/data/teamcity_agent/conf
      - ${AGENT_SYSTEM_VOLUME_DIR}:/data/teamcity_agent/system
    build:
      context: .
      dockerfile: ../teamcity_agent/dockerfile/teamcity_agent.Dockerfile
    networks:
      teamcity-network:
        ipv4_address: 172.20.0.3
