version: 1
disable_existing_loggers: true
formatters:
  info:
    format: '%(asctime)s-%(levelname)s-%(name)s::%(module)s|%(lineno)s:: %(message)s'
  error:
    format: '%(asctime)s-%(levelname)s-%(name)s-%(process)d::%(module)s|%(lineno)s:: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: info
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: info
    filename: logs/info.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8
  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: error
    filename: logs/error.log
    maxBytes: 10485760
    backupCount: 20
    encoding: utf8

loggers:
    root:
        level: INFO
        handlers: [console, file, error_file]
    TeamCityProject:
        level: INFO
        handlers: [console, file, error_file]
        propagate: no
    __main__:
        level: DEBUG
        handlers: [console, file, error_file]
        propagate: no

