teamcity:
  server:
    data_folder: "./teamcity/server/data"
    logs_folder: "./teamcity/server/logs"
  agent:
    conf_folder: "./teamcity/agent/conf"
    system_folder: "./teamcity/agent/system"
  database:
    data_folder: "./teamcity/database/data"